### ISSUE TITLE
Clean UP & Dockerization eos3sa2

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos3sa2#1]

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron, 
This model failed to work initially. Both on CLI and [Colab](https://colab.research.google.com/drive/13t7vJyrLLH5Do9wJWvtQuhwSWQh6yN03?ouid=112369338716777334554&usp=drive_link) with` ModuleNotFoundError: No module named 'pandas'`. 
I decided to setup a local environment for it and test using the local repository. 
The packages were taking long to install, but I was able to fix this by installing torch and scikit-learn using pip instead of conda.
```
RUN conda install -c conda-forge dpu-utils 
RUN pip install torch torchaudio torchvision
RUN pip install rdkit
RUN pip install pandas
RUN pip install py-repo-root
RUN pip install pyprojroot
RUN pip install more-itertools
RUN pip install torch-scatter
RUN pip install sqlalchemy==1.3.24
RUN pip install scikit-learn==0.23.2
```
The issue am facing now is that there happens to be some file, that the model was using, but it is nolonger in the repository because I'm getting the FileNotFoundError. Both when I run the model inside the frameworks folder, and when I fetch it locally.
[eos3sa2_fetch_repo.log](https://github.com/ersilia-os/eos3sa2/files/11903268/eos3sa2_fetch_repo.log)
```
    embeddings = list(csv.reader(open(os.path.join(root, "embeddings.csv"))))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hellenah/eos/repository/eos3sa2/20230628234529_0CA357/eos3sa2/artifacts/framework/code/embeddings.csv'
```
I will try to navigate the repo hsitory and check if the said file ever existed.

**Comment by GemmaTuron** [comment]
@HellenNamulinda,

Apologies, I think this model was not completed by the original contributor, Amna, and it is not working. I think it is fairly complex to start with so I suggest we skip it. 
Sorry for the confusion, I'll assign another one
@miquelduranfrigola meanwhile can you please check the status of this model? It does not even have a metadata file

**Comment by miquelduranfrigola** [comment]
Thanks. The error that @HellenNamulinda is describing is quite specific, so we should reach out to @Amna-28 and see if she is able to provide feedback.

I recall this model being extremely challenging. So, in my opinion, if @Amna-28 is not able to provide a quick easy fix (likely related to a missing file), then we should archive the model. The lightweight alternative (Ersilia Compound Embedding) that Ank developed is probably good enough for most purposes.

So, @HellenNamulinda - please do not work on it until we get feedback from Amna. Fantastic work as usual.

**Comment by HellenNamulinda** [comment]
Yes @miquelduranfrigola,
This model is onhold for now.
